export const releaseUITheme = {
  "glassAlpha": 0.35,
  "glassBlur": 4,
  "glassBorderAlpha": 0.2,
  "glassBorderAccent": "#0099ff",
  "glassTintColor": "#000000",
  "cardRadius": 24,
  "cardShadowOpacity": 0.45,
  "buttonPrimaryBg": "#ccd6dc",
  "buttonPrimaryText": "#05111f",
  "buttonPrimaryBorder": "#2f9400",
  "buttonPrimaryGlow": "#0099ff",
  "buttonSecondaryBg": "#0c1930",
  "buttonSecondaryText": "#eff6ff",
  "buttonSecondaryBorder": "#2f9400",
  "buttonSecondaryGlow": "#4b7bff",
  "textPrimaryColor": "#d8e2f1",
  "textSecondaryColor": "#f5f9ff",
  "textMutedColor": "#90a4bf",
  "fontSizePrimary": 16,
  "fontSizeSecondary": 64,
  "heroTitleMaxWidth": 14,
  "sectionTitleMaxWidth": 30,
  "cardTitleMaxWidth": 24,
  "heroTopOffset": 0,
  "phoneImageScale": 1,
  "fontDisplay": "Space Grotesk",
  "fontBody": "Inter"
} as const

export const releaseBackgroundSphere = {
  "sphereScale": 2,
  "surfacePointSize": 0.04,
  "surfacePointCount": 1600,
  "rotationSpeed": 0.15,
  "rotationDirection": "counterclockwise",
  "gradientColorA": "#ff0000",
  "gradientColorB": "#0099ff",
  "gradientColorC": "#51f889",
  "gradientFlowSpeed": 0.8,
  "logoScale": 2,
  "connectionRatio": 0.06,
  "connectionDepth": 4,
  "connectionGrowSpeed": 0.4
} as const
